# -*- coding: utf-8 -*-
"""LECTURE_UNET_TO_YOLO_BYME.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oj0dwWvRtVm3xJCxmV3FhUcPPzsewZDF

#BINARY UNET
"""

# Import necessary libraries
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, UpSampling2D, Concatenate
from tensorflow.keras.utils import plot_model

# Define a UNet class
class UNet:
    # Initialize the class with an input shape
    def __init__(self, input_shape=(28, 28, 1)):
        self.input_shape = input_shape  # Save the input shape as a class variable
        self.model = self.build_model()  # Call the build_model method to construct the U-Net

    # Define the encoder part of the U-Net
    def encoder(self, inputs):
        # First conv block: apply a 2D convolution with 32 filters, (3,3) kernel size, ReLU activation and same padding,
        # then apply 2D max pooling with (2,2) pool size
        conv1 = Conv2D(32, (3, 3), activation='relu', padding='same')(inputs)
        pool1 = MaxPooling2D(pool_size=(2, 2))(conv1)

        # Second conv block: similar to the first one but with 64 filters
        conv2 = Conv2D(64, (3, 3), activation='relu', padding='same')(pool1)
        pool2 = MaxPooling2D(pool_size=(2, 2))(conv2)

        # Return the outputs of the two conv blocks and the final pooled output
        return conv1, conv2, pool2

    # Define the decoder part of the U-Net
    def decoder(self, conv1, conv2, encoded):
        # First upscaling block: apply 2D upsampling with (2,2) size to the encoded input,
        # concatenate the result with the output of the second conv block from the encoder,
        # then apply a 2D convolution with 64 filters, (3,3) kernel size, ReLU activation and same padding
        up1 = UpSampling2D(size=(2, 2))(encoded)
        merge1 = Concatenate(axis=3)([conv2, up1])
        conv3 = Conv2D(64, (3, 3), activation='relu', padding='same')(merge1)

        # Second upscaling block: similar to the first one but concatenating with the output of the first conv block from the encoder and using 32 filters
        up2 = UpSampling2D(size=(2, 2))(conv3)
        merge2 = Concatenate(axis=3)([conv1, up2])
        conv4 = Conv2D(32, (3, 3), activation='relu', padding='same')(merge2)

        # Return the output of the second conv block
        return conv4

    # Build the complete U-Net model
    def build_model(self):
        # Define the input layer with the input shape
        inputs = Input(self.input_shape)

        # Call the encoder method and pass the inputs to it
        conv1, conv2, encoded = self.encoder(inputs)

        # Call the decoder method and pass the outputs of the encoder to it
        decoded = self.decoder(conv1, conv2, encoded)

        # Define the output layer: apply a 2D convolution with 1 filter (since this is a binary segmentation),
        # (3,3) kernel size, sigmoid activation (to output probabilities) and same padding
        outputs = Conv2D(1, (3, 3), activation='sigmoid', padding='same')(decoded)

        model = Model(inputs=inputs, outputs=outputs)

        model.summary()
        # Return a Model object that includes the inputs and outputs
        return model

    # Compile the model
    def compile(self, optimizer='adam', loss='binary_crossentropy'):
        # Use the compile method of the Model class to compile the model.
        # The optimizer controls the learning rate and the loss function calculates the difference between the
        # model's predictions and the true values
        self.model.compile(optimizer=optimizer, loss=loss)

    # Train the model
    def train(self, x, y, epochs=10, batch_size=128, validation_split=0.1):
        # Use the fit method of the Model class to train the model.
        # x is the input data, y is the target data, epochs is the number of times to iterate over the entire dataset,
        # batch_size is the number of samples per gradient update, and validation_split fraction of the data to use as validation data.
        self.model.fit(x, y, epochs=epochs, batch_size=batch_size, validation_split=validation_split)

    # Use the model to make predictions
    def predict(self, x):
        # Use the predict method of the Model class to generate output predictions for the input samples.
        return self.model.predict(x)

    def finetune(self, train_images, train_masks, validation_images, validation_masks, batch_size=16, epochs=50):
        # Compile the model
        self.model.compile(optimizer='adam', loss=dice_loss, metrics=['accuracy', iou_metric])

        # Define callbacks
        callbacks = [
            EarlyStopping(patience=5, restore_best_weights=True),
            ModelCheckpoint('model_checkpoint.h5', save_best_only=True),
        ]

        # Train the model
        self.model.fit(
            train_images, train_masks,
            validation_data=(validation_images, validation_masks),
            batch_size=batch_size,
            epochs=epochs,
            callbacks=callbacks
        )

        # Load the best checkpointed model
        self.model.load_weights('model_checkpoint.h5')

        # Evaluate the model on test data
        test_loss, test_accuracy, test_iou = self.model.evaluate(test_images, test_masks)
        print('Test Loss:', test_loss)
        print('Test Accuracy:', test_accuracy)
        print('Test IoU:', test_iou)

    def _lr_scheduler(self, epoch):
        initial_learning_rate = 0.001
        decay_steps = 5
        decay_rate = 0.1
        return initial_learning_rate * decay_rate ** (epoch // decay_steps)

    def plot_model(self, filename='unet_model.png'):
        plot_model(self.model, to_file=filename, show_shapes=True)

from tensorflow.keras.datasets.mnist import load_data


# Load MNIST dataset
(train_images, train_labels), (test_images, test_labels) = load_data()

# Normalize pixel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0

# Reshape the images to be (28, 28, 1)
train_images = train_images.reshape((train_images.shape[0], 28, 28, 1))
test_images = test_images.reshape((test_images.shape[0], 28, 28, 1))

# Create binary masks for segmentation
train_masks = (train_images > 0).astype(int)
test_masks = (test_images > 0).astype(int)

# Initialize and train the model
unet = UNet()
unet.plot_model()
unet.compile(loss=loss_function)
unet.train(train_images, train_masks, epochs=1)

import matplotlib.pyplot as plt

fig, axs = plt.subplots(1, 2, figsize=(10, 5))  # 1 row, 2 columns

# Plot the first image
axs[0].imshow(train_images[0])
axs[0].set_title('Train Image')

# Plot the second image
axs[1].imshow(train_masks[0])
axs[1].set_title('Train Mask')

# Remove the x and y ticks
for ax in axs:
    ax.set_xticks([])
    ax.set_yticks([])

plt.show()

import matplotlib.pyplot as plt

fig, axs = plt.subplots(1, 2, figsize=(10, 5))  # 1 row, 2 columns

# Plot the first image
axs[0].imshow(test_images[0])
axs[0].set_title('Test Image')

# Plot the second image
axs[1].imshow(unet.predict(test_images[0].reshape((1,28,28,1))).reshape((28,28,1)))
axs[1].set_title('Predicted Mask')

# Remove the x and y ticks
for ax in axs:
    ax.set_xticks([])
    ax.set_yticks([])

plt.show()

"""#MULTICLASS UNET"""

def mask_to_rgb(mask):
    color_map = np.array([
        [0, 0, 255],    # Blue for digit 0
        [0, 255, 0],    # Green for digit 1
        [255, 0, 0],    # Red for digit 2
        [0, 255, 255],  # Cyan for digit 3
        [255, 0, 255],  # Magenta for digit 4
        [255, 255, 0],  # Yellow for digit 5
        [128, 0, 0],    # Maroon for digit 6
        [0, 128, 0],    # Dark Green for digit 7
        [0, 0, 128],    # Navy for digit 8
        [128, 128, 128],# Grey for digit 9
        [255, 255, 255],# White for background
        [0, 0, 0]       # Black for intersection
    ]) / 255
    return (mask @ color_map).clip(0, 1)

import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist
import numpy as np

# Load MNIST data
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize the images to [0, 1]
x_train = x_train.astype('float32') / 255
x_test = x_test.astype('float32') / 255

# Reshape the images to (28, 28, 1)
x_train = np.expand_dims(x_train, axis=-1)
x_test = np.expand_dims(x_test, axis=-1)

# Create a new dataset for multi-digit images
x_train_multi = np.zeros((x_train.shape[0]//2, 28, 28, 1))
x_test_multi = np.zeros((x_test.shape[0]//2, 28, 28, 1))

# Overlay images of digits on top of each other
for i in range(x_train.shape[0]//2):
    x_train_multi[i] = np.maximum(x_train[2*i], x_train[2*i+1])

for i in range(x_test.shape[0]//2):
    x_test_multi[i] = np.maximum(x_test[2*i], x_test[2*i+1])

# Create a new target dataset for multi-digit masks
y_train_multi = np.zeros((y_train.shape[0]//2, 28, 28, 12))
y_test_multi = np.zeros((y_test.shape[0]//2, 28, 28, 12))

# Create masks for each digit and background
for i in range(y_train.shape[0]//2):
    y_train_multi[i, ..., y_train[2*i]] = np.where(x_train[2*i] > 0, 1, 0).squeeze()
    y_train_multi[i, ..., y_train[2*i+1]] = np.where(x_train[2*i+1] > 0, 1, 0).squeeze()
    y_train_multi[i, ..., 10] = np.where(x_train_multi[i] == 0, 1, 0).squeeze() # background mask

for i in range(y_test.shape[0]//2):
    y_test_multi[i, ..., y_test[2*i]] = np.where(x_test[2*i] > 0, 1, 0).squeeze()
    y_test_multi[i, ..., y_test[2*i+1]] = np.where(x_test[2*i+1] > 0, 1, 0).squeeze()
    y_test_multi[i, ..., 10] = np.where(x_test_multi[i] == 0, 1, 0).squeeze() # background mask

# Create interception mask class
intersection_mask_train = (y_train_multi[..., :10].sum(axis=-1) > 1).astype(int)
intersection_mask_test = (y_test_multi[..., :10].sum(axis=-1) > 1).astype(int)

# Where there's intersection, set all digit classes to 0
y_train_multi[..., :10] = y_train_multi[..., :10] * (1 - np.expand_dims(intersection_mask_train, axis=-1))
y_test_multi[..., :10] = y_test_multi[..., :10] * (1 - np.expand_dims(intersection_mask_test, axis=-1))

# Set the intersection class
y_train_multi[..., 11] = intersection_mask_train
y_test_multi[..., 11] = intersection_mask_test

# Create a new target dataset for digit vs background masks
y_train_binary = np.zeros((y_train.shape[0]//4, 28, 28, 12))
y_test_binary = np.zeros((y_test.shape[0]//4, 28, 28, 12))

# Create binary masks for digits and background
for i in range(y_train.shape[0]//4):
    y_train_binary[i, ..., y_train[i]] = np.where(x_train[i] > 0, 1, 0).squeeze()  # digit mask
    y_train_binary[i, ..., 10] = np.where(x_train[i] == 0, 1, 0).squeeze()  # background mask

for i in range(y_test.shape[0]//4):
    y_test_binary[i, ..., y_test[i]] = np.where(x_test[i] > 0, 1, 0).squeeze()  # digit mask
    y_test_binary[i, ..., 10] = np.where(x_test[i] == 0, 1, 0).squeeze()  # background mask


# Now combine the binary and multi-digit masks
y_train_combined = np.concatenate([y_train_binary, y_train_multi], axis=0)
y_test_combined = np.concatenate([y_test_binary, y_test_multi], axis=0)

# Create datasets for binary digit images
x_train_binary = x_train[:x_train.shape[0]//4]
x_test_binary = x_test[:x_test.shape[0]//4]

# Do the same for the images
x_train_combined = np.concatenate([x_train_binary, x_train_multi], axis=0)
x_test_combined = np.concatenate([x_test_binary, x_test_multi], axis=0)

import matplotlib.pyplot as plt

fig, axs = plt.subplots(1, 2, figsize=(10, 5))  # 1 row, 2 columns

picture = 43000

# Plot the first image
axs[0].imshow(x_train_combined[picture])
axs[0].set_title('Train Image')

# Plot the second image
axs[1].imshow(mask_to_rgb(y_train_combined[picture]))
axs[1].set_title('Train Mask')

# Remove the x and y ticks
for ax in axs:
    ax.set_xticks([])
    ax.set_yticks([])

plt.show()

import numpy as np

def get_most_frequent_pixel_value(image_array):
    # Convert the array to grayscale
    image_gray = np.squeeze(image_array)

    # Count the occurrences of each pixel value
    pixel_counts = np.bincount(image_gray.flatten())

    # Determine the most frequent pixel value
    most_frequent_pixel = np.argmax(pixel_counts)

    # Output '1' if the most frequent pixel value is 1, '0' otherwise
    output = '1' if most_frequent_pixel == 1 else '0'

    return output

# Usage example
mask_image_array = np.array([[1, 1, 1],
                             [1, 0, 0],
                             [0, 0, 0]])

result = get_most_frequent_pixel_value(mask_image_array)
print(result)

# Usage example
mask_image_array = np.array([[1, 1, 1],
                             [1, 1, 0],
                             [0, 0, 0]])

result = get_most_frequent_pixel_value(mask_image_array)
print(result)

# Usage example
mask_image_array = np.array([[0, 0, 1],
                             [1, 1, 0],
                             [0, 0, 0]])

result = get_most_frequent_pixel_value(mask_image_array)



import tensorflow as tf
from tensorflow.keras.losses import categorical_crossentropy
from tensorflow.keras.metrics import MeanIoU, IoU

# Define the number of classes for the segmentation task
num_classes = 12

# Initialize Mean Intersection over Union (MeanIoU) metric
mean_iou = MeanIoU(num_classes=num_classes, sparse_y_true=False, sparse_y_pred=False)

# Initialize a list to hold individual Intersection over Union (IoU) metrics for each class
ious = [IoU(num_classes=num_classes, target_class_ids=[i], sparse_y_true=False, sparse_y_pred=False) for i in range(num_classes)]

# Compile the model metrics with accuracy, mean IoU, and individual class IoUs
metrics = ['accuracy', mean_iou] + ious

import tensorflow as tf
from tensorflow.keras.losses import categorical_crossentropy

from tensorflow.keras import backend as K
from tensorflow.keras.utils import get_custom_objects


def dice_coefficient(y_true, y_pred, smooth=1):
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    intersection = K.sum(y_true_f * y_pred_f)
    return (2. * intersection + smooth) / (K.sum(y_true_f) + K.sum(y_pred_f) + smooth)

def dice_loss(y_true, y_pred):
    return 1 - dice_coefficient(y_true, y_pred)

def iou(y_true, y_pred, smooth=1):
    intersection = K.sum(K.abs(y_true * y_pred), axis=-1)
    sum_ = K.sum(K.abs(y_true) + K.abs(y_pred), axis=-1)
    iou = (intersection + smooth) / (sum_ - intersection + smooth)
    return iou

def iou_loss(y_true, y_pred):
    return 1 - iou(y_true, y_pred)

get_custom_objects().update({'dice_loss': dice_loss, 'iou_loss': iou_loss})

# Define Dice Loss Function
def dice_loss(y_true, y_pred):
    smooth = 1.
    y_true_f = tf.reshape(y_true, [-1])
    y_pred_f = tf.reshape(y_pred, [-1])
    intersection = tf.reduce_sum(y_true_f * y_pred_f)
    return 1 - (2. * intersection + smooth) / (tf.reduce_sum(y_true_f) + tf.reduce_sum(y_pred_f) + smooth)

# Custom Loss Function Combining Categorical Crossentropy and Dice Loss
def combined_loss(y_true, y_pred):
    loss = categorical_crossentropy(y_true, y_pred) + dice_loss(y_true, y_pred)
    # print(categorical_crossentropy(y_true, y_pred))
    # print(dice_loss(y_true, y_pred))
    return loss


# Define metrics
metrics = ['accuracy', MeanIoU(num_classes=num_classes, sparse_y_true=False, sparse_y_pred=False)]

from tensorflow.keras.layers import Dropout, BatchNormalization
from tensorflow.keras.callbacks import ReduceLROnPlateau
from tensorflow.keras.optimizers import Adam
# Import necessary libraries
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, UpSampling2D, Concatenate
from tensorflow.keras.utils import plot_model

class UNet:
    def __init__(self, input_shape=(28, 28, 1), num_classes=12):
        self.input_shape = input_shape
        self.num_classes = num_classes
        self.model = self.build_model()

    def encoder(self, inputs):
        conv1 = Conv2D(64, (3, 3), activation='relu', padding='same')(inputs)
        conv1 = BatchNormalization()(conv1)
        conv1 = Dropout(0.1)(conv1)
        pool1 = MaxPooling2D(pool_size=(2, 2))(conv1)

        conv2 = Conv2D(128, (3, 3), activation='relu', padding='same')(pool1)
        conv2 = BatchNormalization()(conv2)
        conv2 = Dropout(0.1)(conv2)
        pool2 = MaxPooling2D(pool_size=(2, 2))(conv2)

        return conv1, conv2, pool2

    def decoder(self, conv1, conv2, encoded):
        up1 = UpSampling2D(size=(2, 2))(encoded)
        merge1 = Concatenate(axis=3)([conv2, up1])
        conv3 = Conv2D(128, (3, 3), activation='relu', padding='same')(merge1)
        conv3 = BatchNormalization()(conv3)
        conv3 = Dropout(0.1)(conv3)

        up2 = UpSampling2D(size=(2, 2))(conv3)
        merge2 = Concatenate(axis=3)([conv1, up2])
        conv4 = Conv2D(64, (3, 3), activation='relu', padding='same')(merge2)
        conv4 = BatchNormalization()(conv4)
        conv4 = Dropout(0.1)(conv4)

        return conv4

    def build_model(self):
        inputs = Input(self.input_shape)
        conv1, conv2, encoded = self.encoder(inputs)
        decoded = self.decoder(conv1, conv2, encoded)
        outputs = Conv2D(self.num_classes, (1, 1), activation='softmax')(decoded)

        model = Model(inputs=inputs, outputs=outputs)

        model.summary()

        return model

    def compile(self, optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy']):
        self.model.compile(optimizer=optimizer, loss=loss, metrics=metrics)

    def train(self, x, y, epochs=1, batch_size=32, validation_split=0.1):
        #self.model.compile(optimizer=Adam(learning_rate=0.0001), loss='dice', metrics=['iou'])

        lr_reducer = ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=5, min_lr=0.00001, verbose=1)

        self.model.fit(x, y, epochs=epochs, batch_size=batch_size, validation_split=validation_split, callbacks=[lr_reducer])

    def predict(self, x):
        return self.model.predict(x)

"""##UNETAUTOENCODER"""

# from tensorflow.keras.layers import Dropout, BatchNormalization
# from tensorflow.keras.callbacks import ReduceLROnPlateau
# from tensorflow.keras.optimizers import Adam
# # Import necessary libraries
# import tensorflow as tf
# from tensorflow.keras.models import Model
# from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, UpSampling2D, Concatenate
# from tensorflow.keras.utils import plot_model

# class UNet:
#     def __init__(self, input_shape=(28, 28, 1), num_classes=12):
#         self.input_shape = input_shape
#         self.num_classes = num_classes
#         self.model = self.build_model()

#     def encoder(self, inputs):
#         conv1 = Conv2D(64, (3, 3), activation='relu', padding='same')(inputs)
#         conv1 = BatchNormalization()(conv1)
#         conv1 = Dropout(0.1)(conv1)
#         pool1 = MaxPooling2D(pool_size=(2, 2))(conv1)

#         conv2 = Conv2D(128, (3, 3), activation='relu', padding='same')(pool1)
#         conv2 = BatchNormalization()(conv2)
#         conv2 = Dropout(0.1)(conv2)
#         pool2 = MaxPooling2D(pool_size=(2, 2))(conv2)

#         return conv1, conv2, pool2

#     def decoder(self, conv1, conv2, encoded):
#         up1 = UpSampling2D(size=(2, 2))(encoded)
#         merge1 = Concatenate(axis=3)([conv2, up1])
#         conv3 = Conv2D(128, (3, 3), activation='relu', padding='same')(merge1)
#         conv3 = BatchNormalization()(conv3)
#         conv3 = Dropout(0.1)(conv3)

#         up2 = UpSampling2D(size=(2, 2))(conv3)
#         merge2 = Concatenate(axis=3)([conv1, up2])
#         conv4 = Conv2D(64, (3, 3), activation='relu', padding='same')(merge2)
#         conv4 = BatchNormalization()(conv4)
#         conv4 = Dropout(0.1)(conv4)

#         return conv4

#     def autoencoder_decoder(self, encoded):
#         # Autoencoder decoder
#         x = Conv2D(128, (3, 3), activation='relu', padding='same')(encoded)
#         x = UpSampling2D(size=(2, 2))(x)
#         x = Conv2D(64, (3, 3), activation='relu', padding='same')(x)
#         x = UpSampling2D(size=(2, 2))(x)
#         decoded_autoencoder = Conv2D(self.input_shape[2], (3, 3), activation='sigmoid', padding='same')(x)
#         return decoded_autoencoder

#     def build_model(self):
#         inputs = Input(self.input_shape)
#         conv1, conv2, encoded = self.encoder(inputs)
#         decoded_unet = self.decoder(conv1, conv2, encoded)
#         decoded_autoencoder = self.autoencoder_decoder(encoded)

#         unet_output = Conv2D(self.num_classes, (1, 1), activation='softmax', name='unet_output')(decoded_unet)
#         autoencoder_output = Conv2D(self.input_shape[2], (3, 3), activation='sigmoid', padding='same', name='autoencoder_output')(decoded_autoencoder)

#         model = Model(inputs=inputs, outputs=[unet_output, autoencoder_output])

#         model.summary()
#         return model

#     def compile(self, optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy']):
#         self.model.compile(optimizer=optimizer, loss=loss, metrics=metrics)

#     def train(self, x, y, epochs=1, batch_size=32, validation_split=0.1):
#         #self.model.compile(optimizer=Adam(learning_rate=0.0001), loss='dice', metrics=['iou'])

#         lr_reducer = ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=5, min_lr=0.00001, verbose=1)

#         self.model.fit(x, [y, y], epochs=epochs, batch_size=batch_size, validation_split=validation_split, callbacks=[lr_reducer])

#     def predict(self, x):
#         return self.model.predict(x)

# unet = UNet()

# metrics = ['accuracy', mean_iou] + ious

# unet.compile(optimizer='adam', loss={'unet_output': 'categorical_crossentropy', 'autoencoder_output': 'mse'}, metrics=['accuracy'])

# unet.train(x_train_combined, y_train_combined, epochs=50, batch_size=64)

# Initialize U-Net model

unet = UNet()

metrics = ['accuracy', mean_iou] + ious

# Compile the model with the custom loss and metrics
unet.compile(optimizer='adam', loss=combined_loss, metrics=metrics)

# Train the model
unet.train(x_train_combined, y_train_combined, epochs=50, batch_size=64)

import matplotlib.pyplot as plt

fig, axs = plt.subplots(1, 2, figsize=(10, 5))  # 1 row, 2 columns

# Plot the first image
axs[0].imshow(x_train_multi[0])
axs[0].set_title('Train Image')

# Plot the second image
axs[1].imshow(mask_to_rgb(y_train_multi[0]))
axs[1].set_title('Train Mask')

# Remove the x and y ticks
for ax in axs:
    ax.set_xticks([])
    ax.set_yticks([])

plt.show()

import matplotlib.pyplot as plt

test_picture = 3003

fig, axs = plt.subplots(1, 3, figsize=(10, 5))  # 1 row, 2 columns

# Plot the first image
axs[0].imshow(x_test_combined[test_picture])
axs[0].set_title('Test Image')

# Plot the second image
axs[1].imshow(mask_to_rgb(y_test_combined[test_picture]))
axs[1].set_title('Test Mask')

# Plot the second image
axs[2].imshow(mask_to_rgb(unet.predict(x_test_combined[test_picture].reshape((1,28,28,1)))).reshape((28,28,3)))
axs[2].set_title('Predicted Mask')

# Remove the x and y ticks
for ax in axs:
    ax.set_xticks([])
    ax.set_yticks([])

plt.show()

fig, axs = plt.subplots(3, 7, figsize=(20, 10))  # 3 rows, 7 columns

test_pictures = np.random.choice(x_test_combined.shape[0], 7, replace=False)

for i, test_picture in enumerate(test_pictures):
    # Plot the test image
    axs[0, i].imshow(x_test_combined[test_picture])
    axs[0, i].set_title('Test Image')

    # Plot the test mask
    axs[1, i].imshow(mask_to_rgb(y_test_combined[test_picture]))
    axs[1, i].set_title('Test Mask')

    # Plot the predicted mask
    prediction = unet.predict(x_test_combined[test_picture].reshape((1,28,28,1)))
    axs[2, i].imshow(mask_to_rgb(prediction).reshape((28,28,3)))
    axs[2, i].set_title('Predicted Mask')

# Remove the x and y ticks
for i in range(3):
    for j in range(7):
        axs[i, j].set_xticks([])
        axs[i, j].set_yticks([])

plt.tight_layout()
plt.show()

"""# YOLO"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from tensorflow.keras.datasets import mnist

# Load MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize pixel values to be between 0 and 1
x_train, x_test = x_train / 255.0, x_test / 255.0

# Reshape images to have the single channel
x_train = np.expand_dims(x_train, -1)
x_test = np.expand_dims(x_test, -1)

# convert class vectors to binary class matrices
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

# Let's generate larger images (56x56) and place the digits randomly
def generate_images_and_boxes(x, y):
    images = np.zeros((len(x), 56, 56, 1))
    boxes = np.zeros((len(x), 4))

    for i, img in enumerate(x):
        # choose a random location to place the digit
        row_offset = np.random.randint(0, 56-28)
        col_offset = np.random.randint(0, 56-28)

        # place the digit
        images[i, row_offset:row_offset+28, col_offset:col_offset+28, :] = img

        # store the bounding box coordinates
        boxes[i] = [row_offset, col_offset, row_offset+28, col_offset+28]

    return images, y, boxes

x_train, y_train_classification, y_train_bounding_box = generate_images_and_boxes(x_train, y_train)
x_test, y_test_classification, y_test_bounding_box = generate_images_and_boxes(x_test, y_test)

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Flatten, Dense, Dropout

class DigitLocalizationModel:
    def __init__(self):
        self.input_shape = (56, 56, 1)
        self.model = self._create_model()

    def _create_model(self):
        input_layer = Input(shape=self.input_shape)

        # Shared layers
        x = Conv2D(32, (3, 3), activation='relu')(input_layer)
        x = MaxPooling2D((2, 2))(x)
        x = Conv2D(64, (3, 3), activation='relu')(x)
        x = MaxPooling2D((2, 2))(x)
        x = Flatten()(x)

        # Classification head
        x_classification = Dense(128, activation='relu')(x)
        classification_output = Dense(10, activation='softmax', name='classification')(x_classification)

        # Regression head
        x_bounding_box = Dense(128, activation='relu')(x)
        bounding_box_output = Dense(4, name='bounding_box')(x_bounding_box)

        # Complete model
        model = Model(input_layer, [classification_output, bounding_box_output])

        # Compile model with two different losses, one for each output, and metrics
        model.compile(optimizer='adam',
                      loss={'classification': 'categorical_crossentropy', 'bounding_box': 'mean_squared_error'},
                      metrics={'classification': 'accuracy'})

        model.summary()

        return model

    def train(self, x_train, y_train_classification, y_train_bounding_box, epochs=10, batch_size=32):
        self.model.fit(x_train, [y_train_classification, y_train_bounding_box], epochs=epochs, batch_size=batch_size)

    def predict(self, x):
        return self.model.predict(x)

import matplotlib.pyplot as plt

# assuming x_test, y_test_classification, y_test_bounding_box are your test data...

# Train the model
model = DigitLocalizationModel()
model.train(x_train, y_train_classification, y_train_bounding_box, epochs=10)

# Make predictions on the test data
classification_predictions, bounding_box_predictions = model.predict(x_test)

# Plot the first 10 test images, their predicted labels and bounding boxes
fig, axs = plt.subplots(2, 5)
fig.tight_layout()

for i, ax in enumerate(axs.flat):
    # Display the image
    ax.imshow(x_test[i].reshape(56, 56), cmap='gray')

    # Display the predicted bounding box
    pred_box = bounding_box_predictions[i]
    rect = plt.Rectangle((pred_box[1], pred_box[0]), pred_box[3]-pred_box[1], pred_box[2]-pred_box[0],
                         linewidth=1, edgecolor='r', facecolor='none')
    ax.add_patch(rect)

    # Display the predicted label
    pred_label = np.argmax(classification_predictions[i])
    ax.set_title(f"Pred: {pred_label}")

plt.show()

"""# DENSENET | RESTNET"""

import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Conv2D, BatchNormalization, Activation, Concatenate, Input, AveragePooling2D, Flatten, MaxPooling2D

class DenseNetMNIST:
    def __init__(self, input_shape=(28, 28, 1), num_classes=10):
        self.input_shape = input_shape
        self.num_classes = num_classes
        self.model = self._build_model()

    def _dense_block(self, x, num_convs, growth_rate):
        for _ in range(num_convs):
            y = Conv2D(growth_rate, kernel_size=3, padding='same')(x)
            y = BatchNormalization()(y)
            y = Activation('relu')(y)
            x = Concatenate()([x, y])
        return x

    def _transition_layer(self, x, reduction):
        num_filters = int(x.shape[-1] * reduction)
        x = BatchNormalization()(x)
        x = Conv2D(num_filters, kernel_size=1)(x)
        x = AveragePooling2D(pool_size=2, strides=2)(x)
        return x

    def _build_model(self):
        input = Input(shape=self.input_shape)
        x = Conv2D(64, kernel_size=7, strides=2, padding='same')(input)
        x = BatchNormalization()(x)
        x = Activation('relu')(x)
        x = MaxPooling2D(pool_size=3, strides=2, padding='same')(x)

        x = self._dense_block(x, num_convs=4, growth_rate=32)
        x = self._transition_layer(x, reduction=0.5)
        x = self._dense_block(x, num_convs=4, growth_rate=32)
        x = BatchNormalization()(x)
        x = Activation('relu')(x)

        x = AveragePooling2D(pool_size=2)(x)
        x = Flatten()(x)
        output = Dense(self.num_classes, activation='softmax')(x)

        model = Model(inputs=input, outputs=output)

        model.summary()

        return model

    def compile(self, optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy']):
        self.model.compile(optimizer=optimizer, loss=loss, metrics=metrics)

    def train(self, x_train, y_train, batch_size=32, epochs=3, validation_data=None):
        self.model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_data=validation_data)

    def evaluate(self, x_test, y_test):
        return self.model.evaluate(x_test, y_test)

# Usage
densenet_mnist = DenseNetMNIST()
densenet_mnist.compile()

# Load and preprocess MNIST data
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)

# Train the model
densenet_mnist.train(x_train, y_train, validation_data=(x_test, y_test))

# Evaluate the model
test_loss, test_accuracy = densenet_mnist.evaluate(x_test, y_test)
print("Test accuracy:", test_accuracy)

import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Conv2D, BatchNormalization, Activation, Add, Input, AveragePooling2D, Flatten, MaxPooling2D

class ResNetMNIST:
    def __init__(self, input_shape=(28, 28, 1), num_classes=10):
        self.input_shape = input_shape
        self.num_classes = num_classes
        self.model = self._build_model()

    def _residual_block(self, x, filters, kernel_size=3, stride=1):
        y = Conv2D(filters, kernel_size=kernel_size, strides=stride, padding='same')(x)
        y = BatchNormalization()(y)
        y = Activation('relu')(y)
        y = Conv2D(filters, kernel_size=kernel_size, strides=1, padding='same')(y)
        y = BatchNormalization()(y)

        if x.shape[-1] != filters:
            x = Conv2D(filters, kernel_size=1, strides=stride, padding='same')(x)

        out = Add()([x, y])
        out = Activation('relu')(out)
        return out

    def _build_model(self):
        input = Input(shape=self.input_shape)
        x = Conv2D(64, kernel_size=7, strides=2, padding='same')(input)
        x = BatchNormalization()(x)
        x = Activation('relu')(x)
        x = MaxPooling2D(pool_size=3, strides=2, padding='same')(x)

        x = self._residual_block(x, 64)
        x = self._residual_block(x, 128, stride=2)
        x = self._residual_block(x, 256, stride=2)

        # Adjust the pool size here to match the feature map size
        x = AveragePooling2D(pool_size=2)(x)  # Changed from pool_size=4 to pool_size=2
        x = Flatten()(x)
        output = Dense(self.num_classes, activation='softmax')(x)

        model = Model(inputs=input, outputs=output)

        model.summary()

        return model


    def compile(self, optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy']):
        self.model.compile(optimizer=optimizer, loss=loss, metrics=metrics)

    def train(self, x_train, y_train, batch_size=32, epochs=3, validation_data=None):
        self.model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_data=validation_data)

    def evaluate(self, x_test, y_test):
        return self.model.evaluate(x_test, y_test)

# Usage
resnet_mnist = ResNetMNIST()
resnet_mnist.compile()

# Load and preprocess MNIST data
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)

# Train the model
resnet_mnist.train(x_train, y_train, validation_data=(x_test, y_test))

# Evaluate the model
test_loss, test_accuracy = resnet_mnist.evaluate(x_test, y_test)
print("Test accuracy:", test_accuracy)

"""# EXAMPLE | BIGGER UNET - DROPOUT, BATCH NORM"""

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, UpSampling2D, Concatenate, Dropout

class UNet:
    def __init__(self, input_shape=(256, 256, 1)):
        self.input_shape = input_shape
        self.model = self.build_model()

    def encoder(self, inputs):
        # First conv block
        conv1 = Conv2D(64, (3, 3), activation='relu', padding='same')(inputs)
        conv1 = Dropout(0.1)(conv1)
        pool1 = MaxPooling2D(pool_size=(2, 2))(conv1)

        # Second conv block
        conv2 = Conv2D(128, (3, 3), activation='relu', padding='same')(pool1)
        conv2 = Dropout(0.1)(conv2)
        pool2 = MaxPooling2D(pool_size=(2, 2))(conv2)

        # Third conv block
        conv3 = Conv2D(256, (3, 3), activation='relu', padding='same')(pool2)
        conv3 = Dropout(0.2)(conv3)
        pool3 = MaxPooling2D(pool_size=(2, 2))(conv3)

        # Fourth conv block
        conv4 = Conv2D(512, (3, 3), activation='relu', padding='same')(pool3)
        conv4 = Dropout(0.2)(conv4)
        pool4 = MaxPooling2D(pool_size=(2, 2))(conv4)

        return conv1, conv2, conv3, conv4, pool4

    def decoder(self, conv1, conv2, conv3, conv4, encoded):
        # First upscaling block
        up1 = UpSampling2D(size=(2, 2))(encoded)
        merge1 = Concatenate(axis=3)([conv4, up1])
        conv5 = Conv2D(512, (3, 3), activation='relu', padding='same')(merge1)

        # Second upscaling block
        up2 = UpSampling2D(size=(2, 2))(conv5)
        merge2 = Concatenate(axis=3)([conv3, up2])
        conv6 = Conv2D(256, (3, 3), activation='relu', padding='same')(merge2)

        # Third upscaling block
        up3 = UpSampling2D(size=(2, 2))(conv6)
        merge3 = Concatenate(axis=3)([conv2, up3])
        conv7 = Conv2D(128, (3, 3), activation='relu', padding='same')(merge3)

        # Fourth upscaling block
        up4 = UpSampling2D(size=(2, 2))(conv7)
        merge4 = Concatenate(axis=3)([conv1, up4])
        conv8 = Conv2D(64, (3, 3), activation='relu', padding='same')(merge4)

        return conv8

    def build_model(self):
        inputs = Input(self.input_shape)
        conv1, conv2, conv3, conv4, encoded = self.encoder(inputs)

        decoded = self.decoder(conv1, conv2, conv3, conv4, encoded)

        # Final Convolution layer to output the segmentation map.
        # It has only one filter because the output is a binary mask.
        outputs = Conv2D(1, (1, 1), activation='sigmoid')(decoded)

        model = Model(inputs=inputs, outputs=outputs)

        model = summary()

        return model

    def compile(self, optimizer='adam', loss='binary_crossentropy'):
        # The compile function is used to configure the learning process.
        # The optimizer is the search technique used to update the weights in your model.
        # Adam is a common choice. The loss function is used to measure the model's performance.
        # Binary cross entropy is a common choice for binary classification problems,
        # like ours, where each pixel is classified as either part of the object or part of the background.
        self.model.compile(optimizer=optimizer, loss=loss)

    def train(self, x, y, epochs=10, batch_size=32, validation_split=0.1):
        # The train function is used to train the model for a fixed number of epochs (iterations on a dataset).
        # x is the input images, y is the target masks.
        # The batch size is the number of samples per gradient update.
        # Validation split fraction of the data to use as validation data.
        self.model.fit(x, y, epochs=epochs, batch_size=batch_size, validation_split=validation_split)

    def predict(self, x):
        # The predict function generates output predictions for the input samples.
        return self.model.predict(x)